dist: trusty
sudo: required
language: node_js
node_js:
  - '12'

os:
  - linux

addons:
  chrome: stable

env:
  global: CODECOV_TOKEN=$CODECOV_TOKEN

before_script:
  - npm install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: unit-tests
      script:
        - npm run unit-tests:lib-coverage
        - npm run unit-tests:lib-codecov

after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi
