name: 'farengeyt451/ngx-tippy-wrapper'

on:
  push:
    branches: [v4.0]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install main dependencies
        run: npm install

      - name: Install lib dependencies
        run: npm install --prefix ./projects/ngx-tippy-wrapper

      - name: Run unit-tests with coverage
        run: npm run unit-tests:lib-coverage

      - name: Upload report to codecov
        run: npm run unit-tests:lib-codecov

      - name: Build npm package
        run: npm run package

      - name: Install lib
        run: npm install /home/runner/work/ngx-tippy-wrapper/ngx-tippy-wrapper/dist/ngx-tippy-wrapper/ngx-tippy-wrapper-**.tgz
      
      - name: Build demo in production mode
        run: npm run build:demo

      - name: Deploy docs and demo
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/ngx-tippy-demo

