name: 'farengeyt451/ngx-tippy-wrapper'

on:
  push:
    branches: [v4.0]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build:lib

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#       - name: Install Google Chrome
#         run: |
#           wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#           echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
#           sudo apt-get update
#           sudo apt-get install -y google-chrome-stable xvfb
      - name: Install main dependencies
        run: npm ci
      - name: Install lib dependencies
        run: npm i --prefix ./projects/ngx-tippy-wrapper
      - name: Run unit-tests with coverage
        run: npm run unit-tests:lib-coverage

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build demo in production mode
        run: npm run build:demo
      - name: Deploy docs and demo
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist/ngx-tippy-demo
